#!/bin/sh /etc/rc.common
START=99

BIN=homeautomation.sh
BIN_CHILD=homeautomation.lua
PID_FILE=/var/run/$BIN.pid
LOG=/var/log/$BIN.log


start() {
        echo "start $0"
        if ps |grep $BIN |grep -v grep &> /dev/null; then
          echo "Already running."
        else
          start-stop-daemon -S -x $BIN -p $PID_FILE -m -b
        fi
}

stop() {
        echo "stop $0"
        if ps |grep $BIN | grep -v grep &> /dev/null; then
          if [ -f $PID_FILE ] ; then 
            kill $(cat $PID_FILE)
            killall $BIN_CHILD
            rm -rf $PID_FILE
          else
            echo "PID file $PID_FILE missing"
          fi
        else
          echo "$BIN not running."
          if [ -f $PID_FILE ] ; then
            echo "PID file $PID_FILE does exist so maybe it crashed."
          fi
        fi
}

restart() {
        echo "restart $0"
        stop
        start
}

